### ISSUE TITLE
Consider merging into queue_classic

### ISSUE THREAD

**Issue by ryandotsmith** [QueueClassic/queue_classic-later#1]
I think there is a lot of interest in seeing this merged into queue_classic. Any objections? Here is the [original thread](https://groups.google.com/forum/#!topic/queue_classic/0LDuYxlOOM0).

**Comment by jipiboily** [comment]
A PR with similar functionality has been merged today in the core and I just added a note about this in the README for this project. Closing the issue.

As a side note, I released 3.1 RC1.
